USE campuspulse;

ALTER TABLE users ADD COLUMN IF NOT EXISTS usn VARCHAR(40) UNIQUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS semester TINYINT UNSIGNED;
ALTER TABLE users ADD COLUMN IF NOT EXISTS section VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS department VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(25);
