import { useEffect, useMemo, useState } from 'react'
import { BrowserRouter, NavLink, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import AdminApp from './AdminApp.jsx'
import { API_BASE } from './config.js'
import { createSocket } from './socketClient.js'


const seedComplaints = [
  { id: 1, title: 'WiFi keeps dropping in Block C', description: 'The network disconnects every few minutes in the third-floor study area.', category: 'WiFi', location: 'Academic Block C', status: 'In Progress', priority: 'High', upvotes: 24, time: '12 min ago', author: 'Aarav Mehta', similar: 8 },
  { id: 2, title: 'Water leakage near the north entrance', description: 'There is a constant leak by the drinking water station. The floor gets slippery.', category: 'Water', location: 'North Entrance', status: 'Acknowledged', priority: 'Critical', upvotes: 31, time: '42 min ago', author: 'Diya Shah', similar: 5 },
  { id: 3, title: 'Canteen tables need cleaning', description: 'Several tables have been left uncleared during the lunch rush.', category: 'Cleanliness', location: 'Central Canteen', status: 'Reported', priority: 'Medium', upvotes: 12, time: '1 hr ago', author: 'Kabir Rao', similar: 3 },
  { id: 4, title: 'Broken projector in Room 204', description: 'The projector turns on but does not display any image from the classroom PC.', category: 'Classroom', location: 'Science Block, 204', status: 'Resolved', priority: 'Low', upvotes: 18, time: '3 hrs ago', author: 'Nisha Jain', similar: 2 },
]
const categories = ['All categories', 'WiFi', 'Water', 'Cleanliness', 'Classroom', 'Security', 'Transport']
const statuses = ['All status', 'Reported', 'Acknowledged', 'In Progress', 'Resolved']
function Icon({ children }) { return <span className="icon" aria-hidden="true">{children}</span> }

export default function App() { return <BrowserRouter><CampusPulseApp /></BrowserRouter> }

function CampusPulseApp() {
  const [session, setSession] = useState(null)
  const [authMode, setAuthMode] = useState('login'); const [accountType, setAccountType] = useState('student'); const [authError, setAuthError] = useState(''); const [authBusy, setAuthBusy] = useState(false); const [registrationChallenge, setRegistrationChallenge] = useState(null)
  const [active, setActive] = useState('Overview'); const [complaints, setComplaints] = useState([])
  const [category, setCategory] = useState('All categories'); const [status, setStatus] = useState('All status'); const [query, setQuery] = useState(''); const [dark, setDark] = useState(false); const [showReport, setShowReport] = useState(false); const [toast, setToast] = useState('')
  const [weather, setWeather] = useState({ temperature: null, label: 'Location unavailable' })
  const [requests, setRequests] = useState([])
  const filtered = useMemo(() => complaints.filter(item => `${item.title} ${item.description} ${item.location}`.toLowerCase().includes(query.toLowerCase()) && (category === 'All categories' || item.category === category) && (status === 'All status' || item.status === status)), [complaints, category, status, query])
  useEffect(() => { const load = async () => { const response = await fetch(`${API_BASE}/auth/session`, { credentials: 'include' }); if (response.ok) setSession(await response.json()) }; load() }, [])
  useEffect(() => { if (!session) return; const load = async () => { try { const response = await fetch(`${API_BASE}/complaints`, { credentials: 'include' }); if (response.ok) setComplaints(await response.json()); else if (response.status !== 401) flash('Unable to load complaints. Retry.') } catch { flash('Unable to load complaints. Retry.') } }; load() }, [session])
  useEffect(() => {
    if (!session) return undefined
    const socket = createSocket()
    const refreshComplaints = async () => {
      const response = await fetch(`${API_BASE}/complaints`, { credentials: 'include' })
      if (response.ok) setComplaints(await response.json())
    }
    socket.on('complaintCreated', refreshComplaints)
    socket.on('statusUpdate', refreshComplaints)
    return () => socket.close()
  }, [session])
  useEffect(() => { if (session?.role !== 'admin') return; const load = async () => { const response = await fetch(`${API_BASE}/admin/requests`, { credentials: 'include' }); if (response.ok) setRequests(await response.json()) }; load() }, [session])
  useEffect(() => { if (!navigator.geolocation) return; navigator.geolocation.getCurrentPosition(async position => { try { const { latitude, longitude } = position.coords; const response = await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${latitude}&longitude=${longitude}&current=temperature_2m,weather_code`); const data = await response.json(); setWeather({ temperature: Math.round(data.current.temperature_2m), label: `${latitude.toFixed(2)}, ${longitude.toFixed(2)}` }) } catch { setWeather({ temperature: null, label: 'Weather unavailable' }) } }, () => setWeather({ temperature: null, label: 'Location permission off' })) }, [])
  const flash = message => { setToast(message); window.setTimeout(() => setToast(''), 2400) }
  const upvote = async id => { const response = await fetch(`${API_BASE}/complaints/${id}/upvote`, { method: 'POST', credentials: 'include' }); if (response.ok) { const data = await response.json(); setComplaints(items => items.map(item => item.id === id ? { ...item, upvotes: data.upvotes } : item)); flash('Upvote added to the campus pulse') } }
  const changeStatus = async (id, nextStatus) => { const response = await fetch(`${API_BASE}/complaints/${id}/status`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, credentials: 'include', body: JSON.stringify({ status: nextStatus }) }); if (response.ok) { setComplaints(items => items.map(item => item.id === id ? { ...item, status: nextStatus } : item)); flash('Status updated in real time') } }
  const reviewRequest = async (id, nextStatus) => { const response = await fetch(`${API_BASE}/admin/requests/${id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, credentials: 'include', body: JSON.stringify({ status: nextStatus }) }); if (response.ok) { setRequests(items => items.filter(item => item.id !== id)); flash(`Student request ${nextStatus}`) } }
  const addComplaint = async event => { event.preventDefault(); const form = new FormData(event.currentTarget); const payload = Object.fromEntries(form.entries()); const response = await fetch(`${API_BASE}/complaints`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, credentials: 'include', body: JSON.stringify(payload) }); if (response.ok) { setShowReport(false); flash('Report submitted successfully'); const refreshed = await fetch(`${API_BASE}/complaints`, { credentials: 'include' }); if (refreshed.ok) setComplaints(await refreshed.json()) } else { flash('Report could not be submitted') } }
  const authenticate = async event => {
    event.preventDefault(); setAuthError(''); setAuthBusy(true); const form = new FormData(event.currentTarget); const payload = Object.fromEntries(form.entries())
    try {
      const response = await fetch(`${API_BASE}/auth/${authMode === 'register' ? 'start-registration' : 'login'}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, credentials: 'include', body: JSON.stringify({ ...payload, mode: accountType }) })
      const contentType = response.headers.get('content-type') || ''
      const data = contentType.includes('application/json') ? await response.json() : { error: `The API returned an unexpected response (${response.status}). Start the backend on port 5000 and try again.` }
      if (!response.ok) throw new Error(data.error || 'Authentication failed')
      if (authMode === 'register') { setRegistrationChallenge({ ...data, email: payload.email }); setAuthMode('verify-registration'); } else { setSession(data) }
    } catch (error) {
      const unavailableMessage = import.meta.env.DEV
        ? 'Backend unavailable. Start the server on port 5000.'
        : 'CampusPulse service is temporarily unavailable. Please try again.'
      setAuthError(error.message === 'Failed to fetch' ? unavailableMessage : error.message)
    } finally { setAuthBusy(false) }
  }

  const location = useLocation(); const navigate = useNavigate();
  useEffect(() => { if (session && location.pathname === '/') navigate('/dashboard', { replace: true }) }, [session, location.pathname, navigate])

    if (!session) return authMode === 'create-college' ? <CreateCollegeScreen onBack={() => { setAuthError(''); setAccountType('admin'); setAuthMode('login') }} /> : authMode === 'forgot-password' ? <PasswordResetScreen onBack={() => setAuthMode('login')} /> : authMode === 'verify-registration' ? <RegistrationVerificationScreen challenge={registrationChallenge} onComplete={() => { setRegistrationChallenge(null); setAuthMode('login'); setAuthError('Registration verified. Wait for admin approval before signing in.') }} /> : <AuthScreenV2 mode={authMode} accountType={accountType} error={authError} busy={authBusy} onMode={setAuthMode} onType={setAccountType} onSubmit={authenticate} onForgot={() => setAuthMode('forgot-password')} onCreateCollege={() => { setAuthError(''); setAuthMode('create-college') }} />
  function CreateCollegeScreen({ onBack }) { const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [created, setCreated] = useState(null); const [copied, setCopied] = useState(false); const submit = async event => { event.preventDefault(); setError(''); setBusy(true); const payload = Object.fromEntries(new FormData(event.currentTarget).entries()); try { const response = await fetch(`${API_BASE}/auth/create-college`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'College could not be created'); setCreated(data) } catch (requestError) { setError(requestError.message === 'Failed to fetch' ? 'Backend unavailable. Start the server on port 5000.' : requestError.message) } finally { setBusy(false) } }; const copyId = async () => { await navigator.clipboard?.writeText(created.collegeId); setCopied(true) }; if (created) return <div className="auth-screen"><div className="auth-card"><div className="logo auth-logo"><span className="logo-mark">✦</span><span>Campus<span>Pulse</span></span></div><div className="auth-intro"><span className="eyebrow">COLLEGE COMMUNITY CREATED</span><h1>{created.collegeName}</h1><p>Your admin workspace is ready. Save this College ID for student registration.</p></div><div className="college-id-result"><small>COLLEGE ID</small><strong>{created.collegeId}</strong><button type="button" className="auth-switch" onClick={copyId}>{copied ? 'Copied' : 'Copy College ID'}</button></div><button className="button primary auth-submit" onClick={onBack}>Continue to admin login →</button></div></div>; return <div className="auth-screen"><div className="auth-card"><div className="logo auth-logo"><span className="logo-mark">✦</span><span>Campus<span>Pulse</span></span></div><div className="auth-intro"><span className="eyebrow">NEW COLLEGE SETUP</span><h1>Create your college.</h1><p>Set up a private CampusPulse community and become its administrator.</p></div>{error && <div className="auth-error">{error}</div>}<form onSubmit={submit}><label>Admin name<input name="adminName" required placeholder="Admin name" /></label><label>Admin email<input name="adminEmail" type="email" required placeholder="admin@college.edu" /></label><label>Password<input name="adminPassword" type="password" minLength="6" required placeholder="At least 6 characters" /></label><label>Phone number<input name="phone" required placeholder="+91 98765 43210" /></label><label>College name<input name="collegeName" required placeholder="Your college name" /></label><button className="button primary auth-submit" disabled={busy}>{busy ? 'Creating college...' : 'Create college →'}</button></form><button className="auth-switch" onClick={onBack}>Already have an admin account? Sign in</button></div></div> }
  const logout = async () => { await fetch(`${API_BASE}/auth/logout`, { method: 'POST', credentials: 'include' }); setSession(null); navigate('/') }
  if (session.role === 'admin') return <AdminApp session={session} onLogout={logout} dark={dark} setDark={setDark} onReport={() => {}} />
  if (location.pathname !== '/dashboard' && location.pathname !== '/') return <RoutedPageShell session={session} complaints={complaints} requests={requests} dark={dark} setDark={setDark} onLogout={logout} onUpvote={upvote} onStatus={changeStatus} onReport={() => setShowReport(true)} reviewRequest={reviewRequest} />

  return <div className={`app ${dark ? 'dark' : ''}`}>
    <aside className="sidebar"><div className="logo"><span className="logo-mark">✦</span><span>Campus<span>Pulse</span></span></div><div className="workspace-label">WORKSPACE <span>⌄</span></div><nav><SideLink to="/dashboard" icon="⌂" label="Overview" /><SideLink to="/complaints" icon="◈" label="All complaints" /><SideLink to="/my-reports" icon="◷" label="My reports" /><SideLink to="/notifications" icon="♢" label="Notifications" count="3" /></nav><div className="sidebar-bottom"><button className="nav-item" onClick={() => flash('Profile settings coming soon')}><Icon>◎</Icon>Profile</button><button className="nav-item" onClick={() => setDark(!dark)}><Icon>{dark ? '☼' : '☾'}</Icon>{dark ? 'Light mode' : 'Dark mode'}<span className="toggle"><i className={dark ? 'on' : ''} /></span></button><button className="nav-item" onClick={logout}><Icon>↪</Icon>Sign out</button><div className="user"><div className="avatar">{session.user?.name?.slice(0, 2).toUpperCase() || 'CP'}</div><div><strong>{session.user?.name || 'Campus user'}</strong><small>{session.role} account</small></div><span>•••</span></div></div></aside>
    <main className="main"><header className="topbar"><div className="breadcrumb"><span>Workspace</span><b>/</b><strong>{active}</strong></div><div className="top-actions"><button className="icon-button" aria-label="Search"><Icon>⌕</Icon></button><button className="icon-button notification" aria-label="Notifications" onClick={() => setActive('Notifications')}><Icon>♧</Icon><i /></button><button className="button primary" onClick={() => setShowReport(true)}><span>＋</span> Report an issue</button></div></header><div className="content">
      <section className="welcome"><div><div className="eyebrow">CAMPUS {session.role.toUpperCase()} WORKSPACE <span className="live-dot" /> LIVE UPDATES</div><h1>{session.role === 'admin' ? 'Admin operations center' : `Good morning, ${session.user?.name || 'student'}`} <span>✦</span></h1><p>{session.role === 'admin' ? 'Review reports and approve new community members.' : 'Here’s what’s happening across your campus today.'}</p></div><div className="weather"><span>☀</span><div><strong>{weather.temperature === null ? '--' : `${weather.temperature}°`}</strong><small>{weather.label}</small></div></div></section>
      <section className="metrics"><Metric label={session.role === 'admin' ? 'All reports' : 'Campus reports'} value={complaints.length} change="live" icon="◈" tone="blue" /><Metric label="Resolved" value={complaints.filter(item => item.status === 'Resolved').length} change="live" icon="✓" tone="green" /><Metric label={session.role === 'admin' ? 'Needs attention' : 'Your contributions'} value={complaints.filter(item => item.status !== 'Resolved').length} change="live" icon="↗" tone="orange" /><Metric label="Critical issues" value={complaints.filter(item => item.priority === 'Critical').length} change="live" icon="♧" tone="purple" /></section>
      {session.role === 'admin' && <section className="panel request-panel"><div className="panel-heading"><div><h2>Student join requests</h2><p>Approve students from your college community</p></div><strong className="request-count">{requests.length} pending</strong></div>{requests.length === 0 ? <div className="empty">No pending student requests.</div> : requests.map(request => <div className="request-row" key={request.id}><div><strong>{request.name}</strong><small>{request.usn} · Sem {request.semester}, Sec {request.section} · {request.department}</small><small>{request.email}</small></div><div><button className="approve" onClick={() => reviewRequest(request.id, 'approved')}>Approve</button><button className="reject" onClick={() => reviewRequest(request.id, 'rejected')}>Reject</button></div></div>)}</section>}
      {session.role === 'student' && <StudentProgress complaints={complaints} user={session.user} />}
      <section className="dashboard-grid"><div className="panel pulse-panel"><div className="panel-heading"><div><h2>Campus pulse</h2><p>Reported issues over the last 7 days</p></div><select><option>Last 7 days</option><option>Last 30 days</option></select></div><div className="chart"><div className="chart-y"><span>40</span><span>30</span><span>20</span><span>10</span><span>0</span></div><div className="chart-area"><div className="grid-lines"><i /><i /><i /><i /><i /></div><svg viewBox="0 0 700 210" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#5b8cff" stopOpacity=".28" /><stop offset="1" stopColor="#5b8cff" stopOpacity="0" /></linearGradient></defs><path className="area" d="M0,168 C55,160 63,116 115,131 S177,175 230,118 S292,100 345,113 S405,158 460,92 S520,70 575,93 S640,28 700,40 L700,210 L0,210Z" /><path className="line" d="M0,168 C55,160 63,116 115,131 S177,175 230,118 S292,100 345,113 S405,158 460,92 S520,70 575,93 S640,28 700,40" /></svg><div className="chart-x"><span>18 Apr</span><span>19 Apr</span><span>20 Apr</span><span>21 Apr</span><span>22 Apr</span><span>23 Apr</span><span>24 Apr</span></div></div></div></div><div className="panel category-panel"><div className="panel-heading"><div><h2>Reports by category</h2><p>Where attention is needed</p></div><button className="more">•••</button></div><div className="donut-wrap"><div className="donut"><strong>{complaints.length}<small>reports</small></strong></div><div className="legend"><Legend color="#5b8cff" label="Infrastructure" value="38" /><Legend color="#47c98b" label="Cleanliness" value="26" /><Legend color="#ffb84d" label="Utilities" value="22" /><Legend color="#c194ff" label="Other" value="42" /></div></div></div></section>
      <section className="panel reports-panel"><div className="panel-heading reports-heading"><div><h2>{session.role === 'admin' ? 'Complaint management' : 'Latest complaints'}</h2><p>{session.role === 'admin' ? 'Review, prioritize and resolve campus issues.' : 'Stay informed and help your community'}</p></div><button className="text-button" onClick={() => setActive('All complaints')}>View all <span>→</span></button></div><div className="filters"><div className="search"><Icon>⌕</Icon><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search complaints..." /></div><select value={category} onChange={e => setCategory(e.target.value)}>{categories.map(item => <option key={item}>{item}</option>)}</select><select value={status} onChange={e => setStatus(e.target.value)}>{statuses.map(item => <option key={item}>{item}</option>)}</select><button className="filter-button">☷ <span>Filters</span></button></div><div className="table-head"><span>COMPLAINT</span><span>CATEGORY</span><span>STATUS</span><span>PRIORITY</span><span>ACTIVITY</span><span /></div>{filtered.map(item => <Complaint key={item.id} item={item} onUpvote={upvote} onStatus={changeStatus} isAdmin={session.role === 'admin'} />)}{filtered.length === 0 && <div className="empty">No complaints match those filters.</div>}</section>
    </div></main>
    {showReport && <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && setShowReport(false)}><form className="modal" onSubmit={addComplaint}><div className="modal-heading"><div><span className="eyebrow">NEW REPORT</span><h2>What needs attention?</h2></div><button type="button" className="close" onClick={() => setShowReport(false)}>×</button></div><label>Issue title<input name="title" required placeholder="e.g. WiFi is not working in Block C" /></label><label>Location<input name="location" required placeholder="e.g. Academic Block C, 3rd floor" /></label><label>Category<select name="category" defaultValue="WiFi">{categories.slice(1).map(item => <option key={item}>{item}</option>)}</select></label><label>Description<textarea name="description" required placeholder="Tell us what happened and how it affects you..." /></label><div className="ai-note">✦ <span>Our AI will classify this report, detect similar issues, and suggest a priority.</span></div><button className="button primary submit" type="submit">Submit report <span>→</span></button></form></div>}{toast && <div className="toast">✓ <span>{toast}</span></div>}
  </div>
}
function AuthScreen({ mode, accountType, error, busy, onMode, onType, onSubmit }) { return <div className="auth-screen"><div className="auth-glow" /><div className="auth-card"><div className="logo auth-logo"><span className="logo-mark">✦</span><span>Campus<span>Pulse</span></span></div><div className="auth-intro"><span className="eyebrow">CAMPUS COMMUNITY PLATFORM</span><h1>{mode === 'register' ? 'Join your campus.' : 'Welcome back.'}</h1><p>{mode === 'register' ? 'Create your student account to report and track campus issues.' : 'Sign in to keep your campus moving forward.'}</p></div><div className="account-tabs"><button className={accountType === 'student' ? 'selected' : ''} onClick={() => { onType('student'); onMode(mode === 'register' ? 'register' : 'login') }}>Student</button><button className={accountType === 'admin' ? 'selected' : ''} onClick={() => { onType('admin'); onMode('login') }}>Admin</button></div>{error && <div className="auth-error">{error}</div>}<form onSubmit={onSubmit}><label>Email address<input name="email" type="email" required placeholder={accountType === 'admin' ? 'admin@campuspulse.local' : 'you@college.edu'} /></label>{mode === 'register' && accountType === 'student' && <><div className="auth-two"><label>Full name<input name="name" required placeholder="Aarav Mehta" /></label><label>USN / Student ID<input name="usn" required placeholder="1XX22CS001" /></label></div><div className="auth-three"><label>Semester<input name="semester" type="number" min="1" max="12" required placeholder="4" /></label><label>Section<input name="section" required placeholder="A" /></label><label>Department<input name="department" required placeholder="CSE" /></label></div><label>Phone number <span className="optional">optional</span><input name="phone" placeholder="+91 98765 43210" /></label></>}{(mode === 'login' || accountType === 'student') && <label>{accountType === 'admin' ? 'Admin access key' : 'Password'}<input name="password" type="password" required minLength="6" placeholder={accountType === 'admin' ? 'Enter the admin key' : 'At least 6 characters'} /></label>}{mode === 'register' && accountType === 'student' && <label>Password<input name="password" type="password" required minLength="6" placeholder="Create a secure password" /></label>}<button className="button primary auth-submit" disabled={busy}>{busy ? 'Connecting...' : mode === 'register' ? 'Create student account →' : accountType === 'admin' ? 'Enter admin workspace →' : 'Sign in →'}</button></form><button className="auth-switch" onClick={() => { onMode(mode === 'register' ? 'login' : 'register'); onType('student') }}>{mode === 'register' ? 'Already have an account? Sign in' : 'New student? Create an account'}</button><small className="auth-foot">Protected by secure role-based access</small></div></div> }
function AuthScreenV2({ mode, accountType, error, busy, onMode, onType, onSubmit, onForgot, onCreateCollege }) { const registering = mode === 'register' && accountType === 'student'; return <div className="auth-screen"><div className="auth-card"><div className="logo auth-logo"><span className="logo-mark">✦</span><span>Campus<span>Pulse</span></span></div><div className="auth-intro"><span className="eyebrow">CAMPUS COMMUNITY PLATFORM</span><h1>{registering ? 'Join your campus.' : accountType === 'admin' ? 'Admin workspace.' : 'Welcome back.'}</h1><p>{registering ? 'Request access to your college community.' : accountType === 'admin' ? 'Manage reports and approve student requests.' : 'Sign in to track your campus reports.'}</p></div><div className="account-tabs"><button type="button" className={accountType === 'student' ? 'selected' : ''} onClick={() => { onType('student'); onMode(mode === 'register' ? 'register' : 'login') }}>Student</button><button type="button" className={accountType === 'admin' ? 'selected' : ''} onClick={() => { onType('admin'); onMode('login') }}>Admin</button></div>{error && <div className="auth-error">{error}</div>}<form onSubmit={onSubmit}>{registering && <><div className="auth-two"><label>Full name<input name="name" required placeholder="Aarav Mehta" /></label><label>USN / Student ID<input name="usn" required placeholder="1XX22CS001" /></label></div><div className="auth-three"><label>Semester<input name="semester" type="number" min="1" max="12" required placeholder="4" /></label><label>Section<input name="section" required placeholder="A" /></label><label>Department<input name="department" required placeholder="CSE" /></label></div></>}<label>Email address<input name="email" type="email" required placeholder={accountType === 'admin' ? 'admin@college.edu' : 'student@college.edu'} /></label>{(registering || accountType === 'admin') && <label>College code<input name="collegeId" required placeholder="CIT001" /></label>}<label>{accountType === 'admin' ? 'Admin password' : 'Password'}<input name="password" type="password" minLength="10" required placeholder={accountType === 'admin' ? 'Enter admin password' : 'At least 10 characters'} /></label><button className="button primary auth-submit" disabled={busy}>{busy ? 'Connecting...' : registering ? 'Request student access →' : accountType === 'admin' ? 'Enter admin workspace →' : 'Sign in →'}</button></form>{accountType === 'admin' ? <div className="auth-links"><button type="button" className="auth-switch auth-forgot" onClick={onForgot}>Forgot password?</button><button type="button" className="auth-switch" onClick={onCreateCollege}>Create new college / new admin</button></div> : <button className="auth-switch" onClick={() => onMode(registering ? 'login' : 'register')}>{registering ? 'Already have an account? Sign in' : 'New student? Request access'}</button>}<small className="auth-foot">Role-based access • Requests reviewed by college admins</small></div></div> }
function RegistrationVerificationScreen({ challenge, onComplete }) { const [emailCode, setEmailCode] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const submit = async event => { event.preventDefault(); setBusy(true); setError(''); try { const response = await fetch(`${API_BASE}/auth/verify-registration`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, credentials: 'include', body: JSON.stringify({ registrationId: challenge.registrationId, email: challenge.email, emailCode }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Verification failed'); onComplete() } catch (requestError) { setError(requestError.message) } finally { setBusy(false) } }; return <div className="auth-screen"><div className="auth-card"><div className="logo auth-logo"><span className="logo-mark">?</span><span>Campus<span>Pulse</span></span></div><div className="auth-intro"><span className="eyebrow">VERIFY YOUR EMAIL</span><h1>Confirm your email address.</h1><p>Enter the verification code sent to your email.</p></div>{error && <div className="auth-error">{error}</div>}<form onSubmit={submit}><label>Email OTP<input value={emailCode} onChange={event => setEmailCode(event.target.value)} inputMode="numeric" pattern="[0-9]{6}" required placeholder="6-digit email code" /></label><button className="button primary auth-submit" disabled={busy}>{busy ? 'Verifying...' : 'Verify email ?'}</button></form></div></div> }
function PasswordResetScreen({ onBack }) { const [destination, setDestination] = useState(''); const channel = 'email'; const [code, setCode] = useState(''); const [newPassword, setNewPassword] = useState(''); const [sent, setSent] = useState(false); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const request = async event => { event.preventDefault(); setBusy(true); setMessage(''); try { const body = { email: destination }; const response = await fetch(`${API_BASE}/auth/forgot-password`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json(); setMessage(data.message); setSent(true) } catch { setMessage('Unable to request a verification code. Try again.') } finally { setBusy(false) } }; const reset = async event => { event.preventDefault(); setBusy(true); setMessage(''); try { const body = { email: destination }; const response = await fetch(`${API_BASE}/auth/reset-password`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...body, channel, code, newPassword }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Password reset failed'); setMessage('Password updated. You can now sign in.'); setSent(false) } catch (error) { setMessage(error.message) } finally { setBusy(false) } }; return <div className="auth-screen"><div className="auth-card"><div className="logo auth-logo"><span className="logo-mark">✦</span><span>Campus<span>Pulse</span></span></div><div className="auth-intro"><span className="eyebrow">ACCOUNT RECOVERY</span><h1>Reset your password.</h1><p>We will send a verification code if an account matches your details.</p></div>{message && <div className="auth-error">{message}</div>}<form onSubmit={sent ? reset : request}><label>Recovery email<input value={destination} onChange={event => setDestination(event.target.value)} required placeholder={channel === 'email' ? 'admin@college.edu' : '+919876543210'} /></label>{sent && <><label>Verification code<input value={code} onChange={event => setCode(event.target.value)} inputMode="numeric" pattern="[0-9]{6}" required placeholder="6-digit code" /></label><label>New password<input value={newPassword} onChange={event => setNewPassword(event.target.value)} type="password" minLength="10" required placeholder="At least 10 characters" /></label></>}<button className="button primary auth-submit" disabled={busy}>{busy ? 'Please wait...' : sent ? 'Reset password →' : 'Send verification code →'}</button></form><button type="button" className="auth-switch" onClick={onBack}>Back to sign in</button></div></div> }
function SideLink({ to, icon, label, count }) { return <NavLink to={to} className={({ isActive }) => `nav-item${isActive ? ' active' : ''}`}><Icon>{icon}</Icon>{label}{count && <b className="nav-count">{count}</b>}</NavLink> }
function RoutedPageShell({ session, complaints, requests, dark, setDark, onLogout, onUpvote, onStatus, onReport, reviewRequest }) { const location = useLocation(); const title = { '/complaints': 'All Complaints', '/my-reports': 'My Reports', '/notifications': 'Notifications' }[location.pathname] || 'Workspace'; return <div className={`app ${dark ? 'dark' : ''}`}><aside className="sidebar"><div className="logo"><span className="logo-mark">✦</span><span>Campus<span>Pulse</span></span></div><div className="workspace-label">WORKSPACE <span>⌄</span></div><nav><SideLink to="/dashboard" icon="⌂" label="Overview" /><SideLink to="/complaints" icon="◈" label="All complaints" /><SideLink to="/my-reports" icon="◷" label="My reports" /><SideLink to="/notifications" icon="♢" label="Notifications" count="3" /></nav><div className="sidebar-bottom"><button className="nav-item" onClick={() => setDark(!dark)}><Icon>{dark ? '☼' : '☾'}</Icon>{dark ? 'Light mode' : 'Dark mode'}</button><button className="nav-item" onClick={onLogout}><Icon>↪</Icon>Sign out</button><div className="user"><div className="avatar">{session.user?.name?.slice(0, 2).toUpperCase() || 'CP'}</div><div><strong>{session.user?.name || 'Campus user'}</strong><small>{session.role} account</small></div></div></div></aside><main className="main"><header className="topbar"><div className="breadcrumb"><span>Workspace</span><b>/</b><strong>{title}</strong></div><div className="top-actions"><button className="button primary" onClick={onReport}><span>＋</span> Report an issue</button></div></header><Routes><Route path="/complaints" element={<ComplaintsPage complaints={complaints} onUpvote={onUpvote} onStatus={onStatus} isAdmin={session.role === 'admin'} />} /><Route path="/my-reports" element={<MyReportsPage complaints={complaints} user={session.user} />} /><Route path="/notifications" element={<NotificationsPage session={session} />} /></Routes></main></div> }
function PageIntro({ eyebrow, title, description, children }) { return <div className="page-intro"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{children}</div> }
function ComplaintsPage({ complaints, onUpvote, onStatus, isAdmin }) { const [query, setQuery] = useState(''); const [category, setCategory] = useState('All categories'); const [status, setStatus] = useState('All status'); const [priority, setPriority] = useState('All priority'); const filtered = complaints.filter(item => `${item.title} ${item.description} ${item.location}`.toLowerCase().includes(query.toLowerCase()) && (category === 'All categories' || item.category === category) && (status === 'All status' || item.status === status) && (priority === 'All priority' || item.priority === priority)); return <div className="content page-content"><PageIntro eyebrow={isAdmin ? 'CAMPUS DIRECTORY' : 'YOUR REPORTS'} title={isAdmin ? 'All Complaints' : 'My Complaints'} description={isAdmin ? 'Every issue reported across your college community.' : 'Only complaints submitted by your student account are visible here.'} /><div className="panel directory-panel"><div className="filters directory-filters"><div className="search"><Icon>⌕</Icon><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search complaints..." /></div><select value={category} onChange={e => setCategory(e.target.value)}>{categories.map(item => <option key={item}>{item}</option>)}</select><select value={status} onChange={e => setStatus(e.target.value)}>{statuses.map(item => <option key={item}>{item}</option>)}</select><select value={priority} onChange={e => setPriority(e.target.value)}><option>All priority</option><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></div><div className="directory-list">{filtered.map(item => <Complaint key={item.id} item={item} onUpvote={onUpvote} onStatus={onStatus} isAdmin={isAdmin} />)}{!filtered.length && <div className="empty">No complaints match your filters.</div>}</div></div></div> }
function MyReportsPage({ complaints, user }) { const mine = complaints.filter(item => item.author === user?.name || item.user_id === user?.id); const counts = ['Reported', 'Acknowledged', 'In Progress', 'Resolved'].map(status => [status, mine.filter(item => item.status === status).length]); return <div className="content page-content"><PageIntro eyebrow="YOUR ACTIVITY" title="My Reports" description="Track every issue you have raised and its progress." /><div className="mini-metrics">{[['Total reports', mine.length], ...counts.slice(0, 1).map(item => ['Pending', mine.filter(report => report.status !== 'Resolved').length]), ...counts.slice(2, 4).map(item => [item[0], item[1]])].map(([label, value]) => <div className="mini-metric" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="my-report-list">{mine.map(item => <div className="my-report-card" key={item.id}><div className="report-card-top"><div><h2>{item.title}</h2><p>{item.category} · {item.location} · {item.time || 'Recently submitted'}</p></div><span className={`priority priority-${item.priority.toLowerCase()}`}><i />{item.priority}</span></div><div className="timeline">{['Reported', 'Acknowledged', 'In Progress', 'Resolved'].map((step, index) => <div className={['Reported', 'Acknowledged', 'In Progress', 'Resolved'].indexOf(item.status) >= index ? 'timeline-step done' : 'timeline-step'} key={step}><i>{index + 1}</i><span>{step}</span></div>)}</div></div>)}{!mine.length && <div className="panel empty">You have not submitted any reports yet.</div>}</div></div> }
function NotificationsPage({ session }) { const [items, setItems] = useState([]); useEffect(() => { const load = async () => { const response = await fetch(`${API_BASE}/notifications`, { credentials: 'include' }); if (response.ok) setItems(await response.json()) }; load(); const socket = createSocket(); const add = event => { if (event.collegeId !== session.user?.collegeId) return; setItems(current => [{ id: Date.now(), message: event.message || (event.status ? `Your complaint is now ${event.status}.` : 'A new complaint was reported on campus.'), created_at: new Date().toISOString(), is_read: false }, ...current]) }; socket.on('notificationCreated', add); return () => socket.disconnect() }, [session]); const markAll = async () => { await fetch(`${API_BASE}/notifications/read-all`, { method: 'PUT', credentials: 'include' }); setItems(items.map(item => ({ ...item, is_read: true }))) }; return <div className="content page-content"><PageIntro eyebrow="STAY IN THE LOOP" title="Notifications" description="Updates from your campus community and report activity."><button className="text-button" onClick={markAll}>Mark all as read</button></PageIntro><div className="notification-list">{items.map(item => <div className={`notification-card${!item.is_read ? ' unread' : ''}`} key={item.id}><div className="notification-icon">♧</div><div><strong>{item.message}</strong><small>{new Date(item.created_at).toLocaleString()}</small></div><button onClick={async () => { await fetch(`${API_BASE}/notifications/${item.id}/read`, { method: 'PUT', credentials: 'include' }); setItems(items.filter(other => other.id !== item.id)) }}>×</button></div>)}{!items.length && <div className="panel empty">You’re all caught up.</div>}</div></div> }
function StudentProgress({ complaints, user }) { const reports = complaints.filter(item => item.author === user?.name || item.user_id === user?.id).slice(0, 3); const steps = [['Reported', 'Complaint filed'], ['Acknowledged', 'Complaint received'], ['In Progress', 'Technician working'], ['Resolved', 'Resolved']]; return <section className="panel student-progress"><div className="panel-heading"><div><h2>Your complaint progress</h2><p>Follow each report as your college admin moves it forward.</p></div><span className="progress-owner">Admin managed</span></div>{reports.length ? reports.map(item => { const current = steps.findIndex(([status]) => status === item.status); return <div className="progress-report" key={item.id}><div className="progress-report-head"><div><strong>{item.title}</strong><small>{item.category} · {item.location}</small></div><span>{item.status}</span></div><div className="progress-track">{steps.map(([status, label], index) => <div className={`progress-step ${index <= current ? 'done' : ''} ${index === current ? 'current' : ''}`} key={status}><i>{index < current ? '✓' : index + 1}</i><span>{label}</span></div>)}</div></div> }) : <div className="empty">Your submitted complaints will appear here.</div>}</section> }
function Metric({ label, value, change, icon, tone }) { return <div className="metric"><div className={`metric-icon ${tone}`}>{icon}</div><div><p>{label}</p><strong>{value}</strong><small className={tone === 'orange' ? 'neutral' : ''}>↗ {change}</small></div></div> }
function Legend({ color, label, value }) { return <div><span><i style={{ background: color }} />{label}</span><b>{value}</b></div> }
function Complaint({ item, onUpvote, onStatus, isAdmin }) { return <div className="complaint-row"><div className="complaint-main"><div className="complaint-icon">{item.category === 'WiFi' ? '⌁' : item.category === 'Water' ? '◌' : item.category === 'Cleanliness' ? '✧' : '▣'}</div><div><h3>{item.title}</h3><p>{item.description}</p><small>⌖ {item.location} <b>·</b> {item.time} <b>·</b> by {item.author}</small></div></div><span className="category-tag">{item.category}</span>{isAdmin ? <select className={`status status-${item.status.replace(' ', '-').toLowerCase()}`} value={item.status} onChange={e => onStatus(item.id, e.target.value)}>{statuses.slice(1).map(option => <option key={option}>{option}</option>)}</select> : <span className={`status status-${item.status.replace(' ', '-').toLowerCase()}`}>{item.status}</span>}<span className={`priority priority-${item.priority.toLowerCase()}`}><i />{item.priority}</span><div className="activity"><button onClick={() => onUpvote(item.id)}>♧ {item.upvotes}</button><small>{item.similar} similar</small></div><button className="view-details">View details</button></div> }
